#ifndef _QX_EXE_EXPORT_H_
#define _QX_EXE_EXPORT_H_

#ifdef _MSC_VER
#pragma once
#endif

#include "../../dll1/include/export.h"
#include "../../dll2/include/export.h"

#ifdef _QX_BUILDING_EXE
#define QX_REGISTER_HPP_QX_EXE QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_QX_EXE QX_REGISTER_CPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_QX_EXE QX_REGISTER_COMPLEX_CLASS_NAME_HPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_QX_EXE QX_REGISTER_COMPLEX_CLASS_NAME_CPP_EXPORT_DLL
#else // _QX_BUILDING_EXE
#define QX_REGISTER_HPP_QX_EXE QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_QX_EXE QX_REGISTER_CPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_QX_EXE QX_REGISTER_COMPLEX_CLASS_NAME_HPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_QX_EXE QX_REGISTER_COMPLEX_CLASS_NAME_CPP_EXPORT_DLL
#endif // _QX_BUILDING_EXE

#endif // _QX_EXE_EXPORT_H_
