#ifndef _QX_CLIENT_EXPORT_H_
#define _QX_CLIENT_EXPORT_H_

#include "../../qxService/include/export.h"

#ifdef _BUILDING_QX_CLIENT
#define QX_CLIENT_DLL_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_QX_CLIENT
#define QX_CLIENT_DLL_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_QX_CLIENT

#ifdef _BUILDING_QX_CLIENT
#define QX_REGISTER_HPP_QX_CLIENT QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_QX_CLIENT QX_REGISTER_CPP_EXPORT_DLL
#else // _BUILDING_QX_CLIENT
#define QX_REGISTER_HPP_QX_CLIENT QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_QX_CLIENT QX_REGISTER_CPP_IMPORT_DLL
#endif // _BUILDING_QX_CLIENT

#endif // _QX_CLIENT_EXPORT_H_
