/************************************************************************************************
** File created by QxEntityEditor 1.2.3 (2018/11/30 09:04) : please, do NOT modify this file ! **
************************************************************************************************/

#ifndef _KPI_EXPORT_H_
#define _KPI_EXPORT_H_

#ifdef _MSC_VER
#pragma once
#endif

#ifdef _BUILDING_KPI
#define KPI_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_KPI
#define KPI_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_KPI

#ifdef _BUILDING_KPI
#define QX_REGISTER_HPP_KPI QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_KPI QX_REGISTER_CPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_KPI QX_REGISTER_COMPLEX_CLASS_NAME_HPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_KPI QX_REGISTER_COMPLEX_CLASS_NAME_CPP_EXPORT_DLL
#else // _BUILDING_KPI
#define QX_REGISTER_HPP_KPI QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_KPI QX_REGISTER_CPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_KPI QX_REGISTER_COMPLEX_CLASS_NAME_HPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_KPI QX_REGISTER_COMPLEX_CLASS_NAME_CPP_IMPORT_DLL
#endif // _BUILDING_KPI

#ifndef QX_DLL_EXPORT_KPI_SINGLETON_HPP
#ifdef _BUILDING_KPI
#define QX_DLL_EXPORT_KPI_SINGLETON_HPP(x) /* Nothing */
#else // _BUILDING_KPI
#define QX_DLL_EXPORT_KPI_SINGLETON_HPP(x) QX_DLL_EXPORT_TEMPLATE_HPP(class, qx::QxSingleton< x >)
#endif // _BUILDING_KPI
#endif // QX_DLL_EXPORT_KPI_SINGLETON_HPP

#ifndef QX_DLL_EXPORT_KPI_SINGLETON_CPP
#ifdef _BUILDING_KPI
#define QX_DLL_EXPORT_KPI_SINGLETON_CPP(x) QX_DLL_EXPORT_TEMPLATE_CPP(class, qx::QxSingleton< x >)
#else // _BUILDING_KPI
#define QX_DLL_EXPORT_KPI_SINGLETON_CPP(x) /* Nothing */
#endif // _BUILDING_KPI
#endif // QX_DLL_EXPORT_KPI_SINGLETON_CPP

#endif // _KPI_EXPORT_H_
