BEGIN TRANSACTION;
PRAGMA foreign_keys = OFF;
CREATE TABLE t_Child (Child_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, Name TEXT, parent INTEGER, FOREIGN KEY (parent) REFERENCES t_Parent (Parent_id));
CREATE TABLE t_Grandchild (Grandchild_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, Name TEXT, parent INTEGER, FOREIGN KEY (parent) REFERENCES t_Child (Child_id));
CREATE TABLE t_Parent (Parent_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, Name TEXT);
END TRANSACTION;
