#ifndef _CHILDMODELSAVINGBUG_MODEL_VIEW_PRECOMPILED_HEADER_H_CUSTOM
#define _CHILDMODELSAVINGBUG_MODEL_VIEW_PRECOMPILED_HEADER_H_CUSTOM

#ifdef _MSC_VER
#pragma once
#endif

/* -- Put your custom code here -- */

#endif // _CHILDMODELSAVINGBUG_MODEL_VIEW_PRECOMPILED_HEADER_H_CUSTOM
