cd "../"
call "./tools/_clean_debug.bat"
call "./tools/_clean_release.bat"
rmdir /S /Q "./obj/"
del /F /S /Q "./QxOrm.sdf"
del /F /S /Q "./QxOrm.ncb"
del /F /S /Q "./QxOrm.vcproj.A*"
del /F /S /Q "./QxOrm.vcproj.B*"
del /F /S /Q "./QxOrm.vcproj.C*"
del /F /S /Q "./QxOrm.vcproj.D*"
del /F /S /Q "./QxOrm.vcproj.E*"
del /F /S /Q "./QxOrm.vcproj.F*"
del /F /S /Q "./QxOrm.vcproj.G*"
del /F /S /Q "./QxOrm.vcproj.H*"
del /F /S /Q "./QxOrm.vcproj.I*"
del /F /S /Q "./QxOrm.vcproj.J*"
del /F /S /Q "./QxOrm.vcproj.K*"
del /F /S /Q "./QxOrm.vcproj.L*"
del /F /S /Q "./QxOrm.vcproj.M*"
del /F /S /Q "./QxOrm.vcproj.N*"
del /F /S /Q "./QxOrm.vcproj.O*"
del /F /S /Q "./QxOrm.vcproj.P*"
del /F /S /Q "./QxOrm.vcproj.Q*"
del /F /S /Q "./QxOrm.vcproj.R*"
del /F /S /Q "./QxOrm.vcproj.S*"
del /F /S /Q "./QxOrm.vcproj.T*"
del /F /S /Q "./QxOrm.vcproj.U*"
del /F /S /Q "./QxOrm.vcproj.V*"
del /F /S /Q "./QxOrm.vcproj.W*"
del /F /S /Q "./QxOrm.vcproj.X*"
del /F /S /Q "./QxOrm.vcproj.Y*"
del /F /S /Q "./QxOrm.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../"
cd "./test/qxDllSample/"
rmdir /S /Q "./obj/"
del /F /S /Q "./test.sdf"
del /F /S /Q "./test.ncb"
cd "../../test/qxBlog/"
rmdir /S /Q "./obj/"
del /F /S /Q "./qxBlog.sdf"
del /F /S /Q "./qxBlog.ncb"
del /F /S /Q "./qxBlog.vcproj.A*"
del /F /S /Q "./qxBlog.vcproj.B*"
del /F /S /Q "./qxBlog.vcproj.C*"
del /F /S /Q "./qxBlog.vcproj.D*"
del /F /S /Q "./qxBlog.vcproj.E*"
del /F /S /Q "./qxBlog.vcproj.F*"
del /F /S /Q "./qxBlog.vcproj.G*"
del /F /S /Q "./qxBlog.vcproj.H*"
del /F /S /Q "./qxBlog.vcproj.I*"
del /F /S /Q "./qxBlog.vcproj.J*"
del /F /S /Q "./qxBlog.vcproj.K*"
del /F /S /Q "./qxBlog.vcproj.L*"
del /F /S /Q "./qxBlog.vcproj.M*"
del /F /S /Q "./qxBlog.vcproj.N*"
del /F /S /Q "./qxBlog.vcproj.O*"
del /F /S /Q "./qxBlog.vcproj.P*"
del /F /S /Q "./qxBlog.vcproj.Q*"
del /F /S /Q "./qxBlog.vcproj.R*"
del /F /S /Q "./qxBlog.vcproj.S*"
del /F /S /Q "./qxBlog.vcproj.T*"
del /F /S /Q "./qxBlog.vcproj.U*"
del /F /S /Q "./qxBlog.vcproj.V*"
del /F /S /Q "./qxBlog.vcproj.W*"
del /F /S /Q "./qxBlog.vcproj.X*"
del /F /S /Q "./qxBlog.vcproj.Y*"
del /F /S /Q "./qxBlog.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
del /F /S /Q "./*.sqlite"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../"
cd "../../test/qxDllSample/dll1/"
rmdir /S /Q "./obj/"
del /F /S /Q "./dll1.sdf"
del /F /S /Q "./dll1.ncb"
del /F /S /Q "./dll1.vcproj.A*"
del /F /S /Q "./dll1.vcproj.B*"
del /F /S /Q "./dll1.vcproj.C*"
del /F /S /Q "./dll1.vcproj.D*"
del /F /S /Q "./dll1.vcproj.E*"
del /F /S /Q "./dll1.vcproj.F*"
del /F /S /Q "./dll1.vcproj.G*"
del /F /S /Q "./dll1.vcproj.H*"
del /F /S /Q "./dll1.vcproj.I*"
del /F /S /Q "./dll1.vcproj.J*"
del /F /S /Q "./dll1.vcproj.K*"
del /F /S /Q "./dll1.vcproj.L*"
del /F /S /Q "./dll1.vcproj.M*"
del /F /S /Q "./dll1.vcproj.N*"
del /F /S /Q "./dll1.vcproj.O*"
del /F /S /Q "./dll1.vcproj.P*"
del /F /S /Q "./dll1.vcproj.Q*"
del /F /S /Q "./dll1.vcproj.R*"
del /F /S /Q "./dll1.vcproj.S*"
del /F /S /Q "./dll1.vcproj.T*"
del /F /S /Q "./dll1.vcproj.U*"
del /F /S /Q "./dll1.vcproj.V*"
del /F /S /Q "./dll1.vcproj.W*"
del /F /S /Q "./dll1.vcproj.X*"
del /F /S /Q "./dll1.vcproj.Y*"
del /F /S /Q "./dll1.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../../"
cd "../../test/qxDllSample/dll2/"
rmdir /S /Q "./obj/"
del /F /S /Q "./dll2.sdf"
del /F /S /Q "./dll2.ncb"
del /F /S /Q "./dll2.vcproj.A*"
del /F /S /Q "./dll2.vcproj.B*"
del /F /S /Q "./dll2.vcproj.C*"
del /F /S /Q "./dll2.vcproj.D*"
del /F /S /Q "./dll2.vcproj.E*"
del /F /S /Q "./dll2.vcproj.F*"
del /F /S /Q "./dll2.vcproj.G*"
del /F /S /Q "./dll2.vcproj.H*"
del /F /S /Q "./dll2.vcproj.I*"
del /F /S /Q "./dll2.vcproj.J*"
del /F /S /Q "./dll2.vcproj.K*"
del /F /S /Q "./dll2.vcproj.L*"
del /F /S /Q "./dll2.vcproj.M*"
del /F /S /Q "./dll2.vcproj.N*"
del /F /S /Q "./dll2.vcproj.O*"
del /F /S /Q "./dll2.vcproj.P*"
del /F /S /Q "./dll2.vcproj.Q*"
del /F /S /Q "./dll2.vcproj.R*"
del /F /S /Q "./dll2.vcproj.S*"
del /F /S /Q "./dll2.vcproj.T*"
del /F /S /Q "./dll2.vcproj.U*"
del /F /S /Q "./dll2.vcproj.V*"
del /F /S /Q "./dll2.vcproj.W*"
del /F /S /Q "./dll2.vcproj.X*"
del /F /S /Q "./dll2.vcproj.Y*"
del /F /S /Q "./dll2.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../../"
cd "../../test/qxDllSample/exe/"
rmdir /S /Q "./obj/"
del /F /S /Q "./exe.sdf"
del /F /S /Q "./exe.ncb"
del /F /S /Q "./exe.vcproj.A*"
del /F /S /Q "./exe.vcproj.B*"
del /F /S /Q "./exe.vcproj.C*"
del /F /S /Q "./exe.vcproj.D*"
del /F /S /Q "./exe.vcproj.E*"
del /F /S /Q "./exe.vcproj.F*"
del /F /S /Q "./exe.vcproj.G*"
del /F /S /Q "./exe.vcproj.H*"
del /F /S /Q "./exe.vcproj.I*"
del /F /S /Q "./exe.vcproj.J*"
del /F /S /Q "./exe.vcproj.K*"
del /F /S /Q "./exe.vcproj.L*"
del /F /S /Q "./exe.vcproj.M*"
del /F /S /Q "./exe.vcproj.N*"
del /F /S /Q "./exe.vcproj.O*"
del /F /S /Q "./exe.vcproj.P*"
del /F /S /Q "./exe.vcproj.Q*"
del /F /S /Q "./exe.vcproj.R*"
del /F /S /Q "./exe.vcproj.S*"
del /F /S /Q "./exe.vcproj.T*"
del /F /S /Q "./exe.vcproj.U*"
del /F /S /Q "./exe.vcproj.V*"
del /F /S /Q "./exe.vcproj.W*"
del /F /S /Q "./exe.vcproj.X*"
del /F /S /Q "./exe.vcproj.Y*"
del /F /S /Q "./exe.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
del /F /S /Q "./*.db"
del /F /S /Q "./*.xml"
del /F /S /Q "./*.bin"
del /F /S /Q "./*.zip"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../../"
cd "../../test/qxBlogCompositeKey/"
rmdir /S /Q "./obj/"
del /F /S /Q "./qxBlog.sdf"
del /F /S /Q "./qxBlog.ncb"
del /F /S /Q "./qxBlog.vcproj.A*"
del /F /S /Q "./qxBlog.vcproj.B*"
del /F /S /Q "./qxBlog.vcproj.C*"
del /F /S /Q "./qxBlog.vcproj.D*"
del /F /S /Q "./qxBlog.vcproj.E*"
del /F /S /Q "./qxBlog.vcproj.F*"
del /F /S /Q "./qxBlog.vcproj.G*"
del /F /S /Q "./qxBlog.vcproj.H*"
del /F /S /Q "./qxBlog.vcproj.I*"
del /F /S /Q "./qxBlog.vcproj.J*"
del /F /S /Q "./qxBlog.vcproj.K*"
del /F /S /Q "./qxBlog.vcproj.L*"
del /F /S /Q "./qxBlog.vcproj.M*"
del /F /S /Q "./qxBlog.vcproj.N*"
del /F /S /Q "./qxBlog.vcproj.O*"
del /F /S /Q "./qxBlog.vcproj.P*"
del /F /S /Q "./qxBlog.vcproj.Q*"
del /F /S /Q "./qxBlog.vcproj.R*"
del /F /S /Q "./qxBlog.vcproj.S*"
del /F /S /Q "./qxBlog.vcproj.T*"
del /F /S /Q "./qxBlog.vcproj.U*"
del /F /S /Q "./qxBlog.vcproj.V*"
del /F /S /Q "./qxBlog.vcproj.W*"
del /F /S /Q "./qxBlog.vcproj.X*"
del /F /S /Q "./qxBlog.vcproj.Y*"
del /F /S /Q "./qxBlog.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
del /F /S /Q "./*.sqlite"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../"
cd "../../test/qxBlogModelView/"
rmdir /S /Q "./obj/"
del /F /S /Q "./qxBlog.sdf"
del /F /S /Q "./qxBlog.ncb"
del /F /S /Q "./qxBlog.vcproj.A*"
del /F /S /Q "./qxBlog.vcproj.B*"
del /F /S /Q "./qxBlog.vcproj.C*"
del /F /S /Q "./qxBlog.vcproj.D*"
del /F /S /Q "./qxBlog.vcproj.E*"
del /F /S /Q "./qxBlog.vcproj.F*"
del /F /S /Q "./qxBlog.vcproj.G*"
del /F /S /Q "./qxBlog.vcproj.H*"
del /F /S /Q "./qxBlog.vcproj.I*"
del /F /S /Q "./qxBlog.vcproj.J*"
del /F /S /Q "./qxBlog.vcproj.K*"
del /F /S /Q "./qxBlog.vcproj.L*"
del /F /S /Q "./qxBlog.vcproj.M*"
del /F /S /Q "./qxBlog.vcproj.N*"
del /F /S /Q "./qxBlog.vcproj.O*"
del /F /S /Q "./qxBlog.vcproj.P*"
del /F /S /Q "./qxBlog.vcproj.Q*"
del /F /S /Q "./qxBlog.vcproj.R*"
del /F /S /Q "./qxBlog.vcproj.S*"
del /F /S /Q "./qxBlog.vcproj.T*"
del /F /S /Q "./qxBlog.vcproj.U*"
del /F /S /Q "./qxBlog.vcproj.V*"
del /F /S /Q "./qxBlog.vcproj.W*"
del /F /S /Q "./qxBlog.vcproj.X*"
del /F /S /Q "./qxBlog.vcproj.Y*"
del /F /S /Q "./qxBlog.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
del /F /S /Q "./*.sqlite"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../"
cd "../../test/qxBlogCpp11/"
rmdir /S /Q "./obj/"
del /F /S /Q "./qxBlog.sdf"
del /F /S /Q "./qxBlog.ncb"
del /F /S /Q "./qxBlog.vcproj.A*"
del /F /S /Q "./qxBlog.vcproj.B*"
del /F /S /Q "./qxBlog.vcproj.C*"
del /F /S /Q "./qxBlog.vcproj.D*"
del /F /S /Q "./qxBlog.vcproj.E*"
del /F /S /Q "./qxBlog.vcproj.F*"
del /F /S /Q "./qxBlog.vcproj.G*"
del /F /S /Q "./qxBlog.vcproj.H*"
del /F /S /Q "./qxBlog.vcproj.I*"
del /F /S /Q "./qxBlog.vcproj.J*"
del /F /S /Q "./qxBlog.vcproj.K*"
del /F /S /Q "./qxBlog.vcproj.L*"
del /F /S /Q "./qxBlog.vcproj.M*"
del /F /S /Q "./qxBlog.vcproj.N*"
del /F /S /Q "./qxBlog.vcproj.O*"
del /F /S /Q "./qxBlog.vcproj.P*"
del /F /S /Q "./qxBlog.vcproj.Q*"
del /F /S /Q "./qxBlog.vcproj.R*"
del /F /S /Q "./qxBlog.vcproj.S*"
del /F /S /Q "./qxBlog.vcproj.T*"
del /F /S /Q "./qxBlog.vcproj.U*"
del /F /S /Q "./qxBlog.vcproj.V*"
del /F /S /Q "./qxBlog.vcproj.W*"
del /F /S /Q "./qxBlog.vcproj.X*"
del /F /S /Q "./qxBlog.vcproj.Y*"
del /F /S /Q "./qxBlog.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
del /F /S /Q "./*.sqlite"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../"
cd "../../test/qxClientServer/qxClient/"
rmdir /S /Q "./obj/"
del /F /S /Q "./qxClient.sdf"
del /F /S /Q "./qxClient.ncb"
del /F /S /Q "./qxClient.vcproj.A*"
del /F /S /Q "./qxClient.vcproj.B*"
del /F /S /Q "./qxClient.vcproj.C*"
del /F /S /Q "./qxClient.vcproj.D*"
del /F /S /Q "./qxClient.vcproj.E*"
del /F /S /Q "./qxClient.vcproj.F*"
del /F /S /Q "./qxClient.vcproj.G*"
del /F /S /Q "./qxClient.vcproj.H*"
del /F /S /Q "./qxClient.vcproj.I*"
del /F /S /Q "./qxClient.vcproj.J*"
del /F /S /Q "./qxClient.vcproj.K*"
del /F /S /Q "./qxClient.vcproj.L*"
del /F /S /Q "./qxClient.vcproj.M*"
del /F /S /Q "./qxClient.vcproj.N*"
del /F /S /Q "./qxClient.vcproj.O*"
del /F /S /Q "./qxClient.vcproj.P*"
del /F /S /Q "./qxClient.vcproj.Q*"
del /F /S /Q "./qxClient.vcproj.R*"
del /F /S /Q "./qxClient.vcproj.S*"
del /F /S /Q "./qxClient.vcproj.T*"
del /F /S /Q "./qxClient.vcproj.U*"
del /F /S /Q "./qxClient.vcproj.V*"
del /F /S /Q "./qxClient.vcproj.W*"
del /F /S /Q "./qxClient.vcproj.X*"
del /F /S /Q "./qxClient.vcproj.Y*"
del /F /S /Q "./qxClient.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
del /F /S /Q "./*.db"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../../"
cd "../../test/qxClientServer/qxServer/"
rmdir /S /Q "./obj/"
del /F /S /Q "./qxServer.sdf"
del /F /S /Q "./qxServer.ncb"
del /F /S /Q "./qxServer.vcproj.A*"
del /F /S /Q "./qxServer.vcproj.B*"
del /F /S /Q "./qxServer.vcproj.C*"
del /F /S /Q "./qxServer.vcproj.D*"
del /F /S /Q "./qxServer.vcproj.E*"
del /F /S /Q "./qxServer.vcproj.F*"
del /F /S /Q "./qxServer.vcproj.G*"
del /F /S /Q "./qxServer.vcproj.H*"
del /F /S /Q "./qxServer.vcproj.I*"
del /F /S /Q "./qxServer.vcproj.J*"
del /F /S /Q "./qxServer.vcproj.K*"
del /F /S /Q "./qxServer.vcproj.L*"
del /F /S /Q "./qxServer.vcproj.M*"
del /F /S /Q "./qxServer.vcproj.N*"
del /F /S /Q "./qxServer.vcproj.O*"
del /F /S /Q "./qxServer.vcproj.P*"
del /F /S /Q "./qxServer.vcproj.Q*"
del /F /S /Q "./qxServer.vcproj.R*"
del /F /S /Q "./qxServer.vcproj.S*"
del /F /S /Q "./qxServer.vcproj.T*"
del /F /S /Q "./qxServer.vcproj.U*"
del /F /S /Q "./qxServer.vcproj.V*"
del /F /S /Q "./qxServer.vcproj.W*"
del /F /S /Q "./qxServer.vcproj.X*"
del /F /S /Q "./qxServer.vcproj.Y*"
del /F /S /Q "./qxServer.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
del /F /S /Q "./*.db"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../../"
cd "../../test/qxClientServer/qxService/"
rmdir /S /Q "./obj/"
del /F /S /Q "./qxService.sdf"
del /F /S /Q "./qxService.ncb"
del /F /S /Q "./qxService.vcproj.A*"
del /F /S /Q "./qxService.vcproj.B*"
del /F /S /Q "./qxService.vcproj.C*"
del /F /S /Q "./qxService.vcproj.D*"
del /F /S /Q "./qxService.vcproj.E*"
del /F /S /Q "./qxService.vcproj.F*"
del /F /S /Q "./qxService.vcproj.G*"
del /F /S /Q "./qxService.vcproj.H*"
del /F /S /Q "./qxService.vcproj.I*"
del /F /S /Q "./qxService.vcproj.J*"
del /F /S /Q "./qxService.vcproj.K*"
del /F /S /Q "./qxService.vcproj.L*"
del /F /S /Q "./qxService.vcproj.M*"
del /F /S /Q "./qxService.vcproj.N*"
del /F /S /Q "./qxService.vcproj.O*"
del /F /S /Q "./qxService.vcproj.P*"
del /F /S /Q "./qxService.vcproj.Q*"
del /F /S /Q "./qxService.vcproj.R*"
del /F /S /Q "./qxService.vcproj.S*"
del /F /S /Q "./qxService.vcproj.T*"
del /F /S /Q "./qxService.vcproj.U*"
del /F /S /Q "./qxService.vcproj.V*"
del /F /S /Q "./qxService.vcproj.W*"
del /F /S /Q "./qxService.vcproj.X*"
del /F /S /Q "./qxService.vcproj.Y*"
del /F /S /Q "./qxService.vcproj.Z*"
del /F /S /Q "./Makefile*"
del /F /S /Q "./vc90.pdb"
del /F /S /Q "./vc110.pdb"
del /F /S /Q "./*.db"
cd "./qt/moc/"
del /F /S /Q "./*.cpp"
cd "../../../"
cd "../../test/_bin/"
del /F /S /Q "./*.*"
cd "../../test/qxDllSample/dll1/debug/"
del /F /S /Q "./*.*"
cd "../../../../test/qxDllSample/dll1/release/"
del /F /S /Q "./*.*"
cd "../../../../test/qxDllSample/dll2/debug/"
del /F /S /Q "./*.*"
cd "../../../../test/qxDllSample/dll2/release/"
del /F /S /Q "./*.*"
cd "../../../../test/qxDllSample/exe/debug/"
del /F /S /Q "./*.*"
cd "../../../../test/qxDllSample/exe/release/"
del /F /S /Q "./*.*"
cd "../../../../test/qxBlog/debug/"
del /F /S /Q "./*.*"
cd "../../../test/qxBlog/release/"
del /F /S /Q "./*.*"
cd "../../../test/qxBlogCompositeKey/debug/"
del /F /S /Q "./*.*"
cd "../../../test/qxBlogCompositeKey/release/"
del /F /S /Q "./*.*"
cd "../../../test/qxBlogModelView/debug/"
del /F /S /Q "./*.*"
cd "../../../test/qxBlogModelView/release/"
del /F /S /Q "./*.*"
cd "../../../test/qxBlogCpp11/debug/"
del /F /S /Q "./*.*"
cd "../../../test/qxBlogCpp11/release/"
del /F /S /Q "./*.*"
cd "../../../test/qxClientServer/qxClient/debug/"
del /F /S /Q "./*.*"
cd "../../../../test/qxClientServer/qxClient/release/"
del /F /S /Q "./*.*"
cd "../../../../test/qxClientServer/qxServer/debug/"
del /F /S /Q "./*.*"
cd "../../../../test/qxClientServer/qxServer/release/"
del /F /S /Q "./*.*"
cd "../../../../test/qxClientServer/qxService/debug/"
del /F /S /Q "./*.*"
cd "../../../../test/qxClientServer/qxService/release/"
del /F /S /Q "./*.*"
cd "../../../../"
cd "./tools/"
pause
