#ifndef _QX_DLL1_EXPORT_H_
#define _QX_DLL1_EXPORT_H_

#ifdef _MSC_VER
#pragma once
#endif

#ifndef QX_DLL1_EXPORT
#ifdef Q_OS_WIN
#define QX_DLL1_EXPORT __declspec(dllexport)
#else
#define QX_DLL1_EXPORT
#endif
#endif // QX_DLL1_EXPORT

#ifndef QX_DLL1_IMPORT
#ifdef Q_OS_WIN
#define QX_DLL1_IMPORT __declspec(dllimport)
#else
#define QX_DLL1_IMPORT
#endif
#endif // QX_DLL1_IMPORT

#ifdef Q_OS_WIN
#ifndef _QX_BUILDING_DLL1
#ifdef QX_DLL1_EXPORT
#undef QX_DLL1_EXPORT
#endif
#define QX_DLL1_EXPORT QX_DLL1_IMPORT
#endif
#endif // Q_OS_WIN

#ifdef _QX_BUILDING_DLL1
#define QX_REGISTER_HPP_QX_DLL1 QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_QX_DLL1 QX_REGISTER_CPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_QX_DLL1 QX_REGISTER_COMPLEX_CLASS_NAME_HPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_QX_DLL1 QX_REGISTER_COMPLEX_CLASS_NAME_CPP_EXPORT_DLL
#else
#define QX_REGISTER_HPP_QX_DLL1 QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_QX_DLL1 QX_REGISTER_CPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_QX_DLL1 QX_REGISTER_COMPLEX_CLASS_NAME_HPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_QX_DLL1 QX_REGISTER_COMPLEX_CLASS_NAME_CPP_IMPORT_DLL
#endif // _QX_BUILDING_DLL1

#endif // _QX_DLL1_EXPORT_H_
